apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-crm-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-crm-api
  template:
    metadata:
      labels:
        app: customer-crm-api
    spec:
      containers:
      - name: api
        image: ghcr.io/katlegoraymond/customercrmapi:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/customer_crm
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
